// *** AUTOGENERATED BY "go generate" ***

package iptrie

import (
	"fmt"
	"unsafe"
)

type btrienode32 struct {
	a, b      *btrienode32
	data      unsafe.Pointer
	bits      [32 / 32]uint32
	prefixlen byte
	dummy     byte
}

// sweep goes thru whole subtree calling f. Could be used for cleanup,
// e.g.  tree.sweep(func(n *node) { n.a, n.b, n.data = nil, nil, nil })
func (node *btrienode32) sweep(f func(*btrienode32)) {
	if node.a != nil {
		f(node.a)
	}
	if node.b != nil {
		f(node.b)
	}
	f(node)
}

// match returns true if key/ln is valid child of node or node itself
func (node *btrienode32) match(key []uint32, ln byte) bool {
	npl := node.prefixlen
	if ln < npl {
		return false
	}

	if npl != 0 {
		var mask uint32
		if npl%32 != 0 {
			mask = ^(0xffffffff >> (npl % 32))
		} else {
			mask = 0xffffffff
		}
		if npl <= 32 {
			return node.bits[0]&mask == key[0]&mask
		}

		m := int(npl-1) / 32
		for s := m - 1; s >= 0; s-- {
			if node.bits[s] != key[s] {
				return false
			}
		}
		if node.bits[m]&mask != key[m]&mask {
			return false
		}
	}
	return true
}

func (node *btrienode32) bitsMatched(key []uint32, ln byte) byte {
	maxlen := node.prefixlen
	if ln < maxlen {
		maxlen = ln
	}
	if maxlen == 0 {
		return 0
	}
	var n, plen byte
	for n = 0; n < maxlen/32; n++ {
		// how many should be equal?
		if key[n] != node.bits[n] {
			// compare that bit
			break
		}
		plen += 32 // skip checking every bit in this word
	}

	var mask uint32

	for plen < maxlen {
		mask = (mask >> 1) | 0x80000000 // move 1 and set 32nd bit to 1
		if (node.bits[n] & mask) != (key[n] & mask) {
			break
		}
		plen++
	}

	return plen
}

type tree32 struct {
	*btrienode32
	nodes []btrienode32
}

func (t *tree32) newnode(bits []uint32, prefixlen, dummy byte) *btrienode32 {
	if len(t.nodes) == 0 {
		t.nodes = make([]btrienode32, 20) // 20 nodes at once to prepare
	}

	idx := len(t.nodes) - 1
	node := &(t.nodes[idx])
	t.nodes = t.nodes[:idx]

	node.prefixlen, node.dummy = prefixlen, dummy
	copy(node.bits[:], bits)
	return node
}

func (t *tree32) isEmpty() bool {
	return t.btrienode32 == nil
}

func (t *tree32) findBestMatch(key []uint32, ln byte) (bool, *btrienode32, *btrienode32) {
	var (
		exact   bool
		cparent *btrienode32
		parent  *btrienode32
		node    = t.btrienode32
	)
	for node != nil && node.match(key, ln) {
		if parent != nil && parent.dummy == 0 {
			cparent = parent
		}
		if DEBUG != nil {
			if node.dummy != 0 {
				fmt.Fprintf(DEBUG, "dummy %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			} else {
				fmt.Fprintf(DEBUG, "found %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			}
		}
		parent = node
		if node.prefixlen == ln {
			exact = true
			break
		}
		if hasBit(key, parent.prefixlen+1) {
			node = node.a
		} else {
			node = node.b
		}
	}
	return exact, parent, cparent
}

func (t *tree32) addRoute(key []uint32, ln byte, value unsafe.Pointer, replace bool) (set bool, oldval unsafe.Pointer) {
	if ln > 32 {
		panic("Unable to add prefix longer than 32")
	}
	set = true
	if t.btrienode32 == nil {
		// just starting a tree
		if DEBUG != nil {
			fmt.Fprintf(DEBUG, "root=%s (no subtree)\n", keyStr(key, ln))
		}
		t.btrienode32 = t.newnode(key[:(ln+31)/32], ln, 0)
		return
	}
	var (
		exact bool
		node  *btrienode32
		down  *btrienode32
	)
	if exact, node, _ = t.findBestMatch(key, ln); exact {
		if node.dummy != 0 {
			node.dummy = 0
			node.data = value
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "setting empty child's %v/%d value\n", key, ln)
			}
		} else {
			oldval = node.data
			if replace {
				node.data = value
			} else {
				set = false // this is only time we don't set
			}
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "hit previously set %v/%d node\n", key, ln)
			}
		}
		return
	}
	newnode := t.newnode(key[:(ln+31)/32], ln, 0)
	if node != nil {
		if hasBit(key, node.prefixlen+1) {
			if node.a == nil {
				node.a = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "a-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.a
			down = node.a
		} else {
			if node.b == nil {
				node.b = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "b-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.b
			down = node.b
		}
	} else {
		// newnode goes in front of root node
		down = t.btrienode32
	}

	parent := node
	if parent != nil && parent.prefixlen >= ln {
		panic("parent's prefix could not be larger than key len")
	}

	matched := down.bitsMatched(key, ln)
	if matched > ln {
		matched = ln
	}

	if matched == ln { // matched >=ln to remove that if above
		// down matches key fully, so new branch would start from here
		var plen byte = 1
		if parent != nil {
			// also make sure we're not messed up branch direction
			plen = parent.prefixlen + 1
		}
		use_a := hasBit(newnode.bits[:], plen)
		if use_a != hasBit(down.bits[:], plen) {
			panic("something is wrong with branch that we intend to append to")
		}
		if use_a {
			newnode.a = down
		} else {
			newnode.b = down
		}
		if parent != nil {
			if hasBit(newnode.bits[:], plen) {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.a = newnode
			} else {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.b = newnode
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(key, ln), keyStr(down.bits[:], down.prefixlen), m)
			}
			t.btrienode32 = newnode
		}
	} else {
		// down and newnode should have new empty parent
		node = t.newnode(key[:(ln+31)/32], matched, 1)
		use_a := hasBit(down.bits[:], matched+1)
		if use_a == hasBit(newnode.bits[:], matched+1) {
			panic("tangled branches while creating new intermediate parent")
		}
		if use_a {
			node.a = down
			node.b = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created a-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(down.bits[:], down.prefixlen), keyStr(key, ln))
			}
		} else {
			node.b = down
			node.a = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created b-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), keyStr(down.bits[:], down.prefixlen))
			}
		}

		//insert b-child 1.2.3.0/25 to 1.2.3.0/24 before 1.2.3.0/29
		if parent != nil {
			if hasBit(newnode.bits[:], parent.prefixlen+1) {
				parent.a = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.a.bits[:], node.a.prefixlen))
				}
			} else {
				parent.b = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.b.bits[:], node.b.prefixlen))
				}
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), m)
			}
			t.btrienode32 = node
		}
	}
	return
}

func New32() *Trie32 {
	return &Trie32{new(tree32)}
}

func (rt *Trie32) Get(ip []byte, mask byte) (bool, []byte, byte, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	exact, node, ct := rt.findBestMatch(u32, mask)

	if node != nil && node.dummy == 0 {
		// dummy node means "no match"
		return exact, utoip(node.bits[:], node.prefixlen), node.prefixlen, node.data
	}

	if ct != nil {
		// accept container as the answer if it's present
		return false, utoip(ct.bits[:], ct.prefixlen), ct.prefixlen, ct.data
	}
	return false, nil, 0, nil

}

func (rt *Trie32) Append(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, false)
	return set, olval
}

func (rt *Trie32) Set(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, true)
	return set, olval
}

type btrienode64 struct {
	a, b      *btrienode64
	data      unsafe.Pointer
	bits      [64 / 32]uint32
	prefixlen byte
	dummy     byte
}

// sweep goes thru whole subtree calling f. Could be used for cleanup,
// e.g.  tree.sweep(func(n *node) { n.a, n.b, n.data = nil, nil, nil })
func (node *btrienode64) sweep(f func(*btrienode64)) {
	if node.a != nil {
		f(node.a)
	}
	if node.b != nil {
		f(node.b)
	}
	f(node)
}

// match returns true if key/ln is valid child of node or node itself
func (node *btrienode64) match(key []uint32, ln byte) bool {
	npl := node.prefixlen
	if ln < npl {
		return false
	}

	if npl != 0 {
		var mask uint32
		if npl%32 != 0 {
			mask = ^(0xffffffff >> (npl % 32))
		} else {
			mask = 0xffffffff
		}
		if npl <= 32 {
			return node.bits[0]&mask == key[0]&mask
		}

		m := int(npl-1) / 32
		for s := m - 1; s >= 0; s-- {
			if node.bits[s] != key[s] {
				return false
			}
		}
		if node.bits[m]&mask != key[m]&mask {
			return false
		}
	}
	return true
}

func (node *btrienode64) bitsMatched(key []uint32, ln byte) byte {
	maxlen := node.prefixlen
	if ln < maxlen {
		maxlen = ln
	}
	if maxlen == 0 {
		return 0
	}
	var n, plen byte
	for n = 0; n < maxlen/32; n++ {
		// how many should be equal?
		if key[n] != node.bits[n] {
			// compare that bit
			break
		}
		plen += 32 // skip checking every bit in this word
	}

	var mask uint32

	for plen < maxlen {
		mask = (mask >> 1) | 0x80000000 // move 1 and set 32nd bit to 1
		if (node.bits[n] & mask) != (key[n] & mask) {
			break
		}
		plen++
	}

	return plen
}

type tree64 struct {
	*btrienode64
	nodes []btrienode64
}

func (t *tree64) newnode(bits []uint32, prefixlen, dummy byte) *btrienode64 {
	if len(t.nodes) == 0 {
		t.nodes = make([]btrienode64, 20) // 20 nodes at once to prepare
	}

	idx := len(t.nodes) - 1
	node := &(t.nodes[idx])
	t.nodes = t.nodes[:idx]

	node.prefixlen, node.dummy = prefixlen, dummy
	copy(node.bits[:], bits)
	return node
}

func (t *tree64) isEmpty() bool {
	return t.btrienode64 == nil
}

func (t *tree64) findBestMatch(key []uint32, ln byte) (bool, *btrienode64, *btrienode64) {
	var (
		exact   bool
		cparent *btrienode64
		parent  *btrienode64
		node    = t.btrienode64
	)
	for node != nil && node.match(key, ln) {
		if parent != nil && parent.dummy == 0 {
			cparent = parent
		}
		if DEBUG != nil {
			if node.dummy != 0 {
				fmt.Fprintf(DEBUG, "dummy %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			} else {
				fmt.Fprintf(DEBUG, "found %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			}
		}
		parent = node
		if node.prefixlen == ln {
			exact = true
			break
		}
		if hasBit(key, parent.prefixlen+1) {
			node = node.a
		} else {
			node = node.b
		}
	}
	return exact, parent, cparent
}

func (t *tree64) addRoute(key []uint32, ln byte, value unsafe.Pointer, replace bool) (set bool, oldval unsafe.Pointer) {
	if ln > 64 {
		panic("Unable to add prefix longer than 64")
	}
	set = true
	if t.btrienode64 == nil {
		// just starting a tree
		if DEBUG != nil {
			fmt.Fprintf(DEBUG, "root=%s (no subtree)\n", keyStr(key, ln))
		}
		t.btrienode64 = t.newnode(key[:(ln+31)/32], ln, 0)
		return
	}
	var (
		exact bool
		node  *btrienode64
		down  *btrienode64
	)
	if exact, node, _ = t.findBestMatch(key, ln); exact {
		if node.dummy != 0 {
			node.dummy = 0
			node.data = value
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "setting empty child's %v/%d value\n", key, ln)
			}
		} else {
			oldval = node.data
			if replace {
				node.data = value
			} else {
				set = false // this is only time we don't set
			}
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "hit previously set %v/%d node\n", key, ln)
			}
		}
		return
	}
	newnode := t.newnode(key[:(ln+31)/32], ln, 0)
	if node != nil {
		if hasBit(key, node.prefixlen+1) {
			if node.a == nil {
				node.a = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "a-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.a
			down = node.a
		} else {
			if node.b == nil {
				node.b = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "b-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.b
			down = node.b
		}
	} else {
		// newnode goes in front of root node
		down = t.btrienode64
	}

	parent := node
	if parent != nil && parent.prefixlen >= ln {
		panic("parent's prefix could not be larger than key len")
	}

	matched := down.bitsMatched(key, ln)
	if matched > ln {
		matched = ln
	}

	if matched == ln { // matched >=ln to remove that if above
		// down matches key fully, so new branch would start from here
		var plen byte = 1
		if parent != nil {
			// also make sure we're not messed up branch direction
			plen = parent.prefixlen + 1
		}
		use_a := hasBit(newnode.bits[:], plen)
		if use_a != hasBit(down.bits[:], plen) {
			panic("something is wrong with branch that we intend to append to")
		}
		if use_a {
			newnode.a = down
		} else {
			newnode.b = down
		}
		if parent != nil {
			if hasBit(newnode.bits[:], plen) {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.a = newnode
			} else {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.b = newnode
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(key, ln), keyStr(down.bits[:], down.prefixlen), m)
			}
			t.btrienode64 = newnode
		}
	} else {
		// down and newnode should have new empty parent
		node = t.newnode(key[:(ln+31)/32], matched, 1)
		use_a := hasBit(down.bits[:], matched+1)
		if use_a == hasBit(newnode.bits[:], matched+1) {
			panic("tangled branches while creating new intermediate parent")
		}
		if use_a {
			node.a = down
			node.b = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created a-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(down.bits[:], down.prefixlen), keyStr(key, ln))
			}
		} else {
			node.b = down
			node.a = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created b-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), keyStr(down.bits[:], down.prefixlen))
			}
		}

		//insert b-child 1.2.3.0/25 to 1.2.3.0/24 before 1.2.3.0/29
		if parent != nil {
			if hasBit(newnode.bits[:], parent.prefixlen+1) {
				parent.a = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.a.bits[:], node.a.prefixlen))
				}
			} else {
				parent.b = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.b.bits[:], node.b.prefixlen))
				}
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), m)
			}
			t.btrienode64 = node
		}
	}
	return
}

func New64() *Trie64 {
	return &Trie64{new(tree64)}
}

func (rt *Trie64) Get(ip []byte, mask byte) (bool, []byte, byte, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	exact, node, ct := rt.findBestMatch(u32, mask)

	if node != nil && node.dummy == 0 {
		// dummy node means "no match"
		return exact, utoip(node.bits[:], node.prefixlen), node.prefixlen, node.data
	}

	if ct != nil {
		// accept container as the answer if it's present
		return false, utoip(ct.bits[:], ct.prefixlen), ct.prefixlen, ct.data
	}
	return false, nil, 0, nil

}

func (rt *Trie64) Append(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, false)
	return set, olval
}

func (rt *Trie64) Set(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, true)
	return set, olval
}

type btrienode128 struct {
	a, b      *btrienode128
	data      unsafe.Pointer
	bits      [128 / 32]uint32
	prefixlen byte
	dummy     byte
}

// sweep goes thru whole subtree calling f. Could be used for cleanup,
// e.g.  tree.sweep(func(n *node) { n.a, n.b, n.data = nil, nil, nil })
func (node *btrienode128) sweep(f func(*btrienode128)) {
	if node.a != nil {
		f(node.a)
	}
	if node.b != nil {
		f(node.b)
	}
	f(node)
}

// match returns true if key/ln is valid child of node or node itself
func (node *btrienode128) match(key []uint32, ln byte) bool {
	npl := node.prefixlen
	if ln < npl {
		return false
	}

	if npl != 0 {
		var mask uint32
		if npl%32 != 0 {
			mask = ^(0xffffffff >> (npl % 32))
		} else {
			mask = 0xffffffff
		}
		if npl <= 32 {
			return node.bits[0]&mask == key[0]&mask
		}

		m := int(npl-1) / 32
		for s := m - 1; s >= 0; s-- {
			if node.bits[s] != key[s] {
				return false
			}
		}
		if node.bits[m]&mask != key[m]&mask {
			return false
		}
	}
	return true
}

func (node *btrienode128) bitsMatched(key []uint32, ln byte) byte {
	maxlen := node.prefixlen
	if ln < maxlen {
		maxlen = ln
	}
	if maxlen == 0 {
		return 0
	}
	var n, plen byte
	for n = 0; n < maxlen/32; n++ {
		// how many should be equal?
		if key[n] != node.bits[n] {
			// compare that bit
			break
		}
		plen += 32 // skip checking every bit in this word
	}

	var mask uint32

	for plen < maxlen {
		mask = (mask >> 1) | 0x80000000 // move 1 and set 32nd bit to 1
		if (node.bits[n] & mask) != (key[n] & mask) {
			break
		}
		plen++
	}

	return plen
}

type tree128 struct {
	*btrienode128
	nodes []btrienode128
}

func (t *tree128) newnode(bits []uint32, prefixlen, dummy byte) *btrienode128 {
	if len(t.nodes) == 0 {
		t.nodes = make([]btrienode128, 20) // 20 nodes at once to prepare
	}

	idx := len(t.nodes) - 1
	node := &(t.nodes[idx])
	t.nodes = t.nodes[:idx]

	node.prefixlen, node.dummy = prefixlen, dummy
	copy(node.bits[:], bits)
	return node
}

func (t *tree128) isEmpty() bool {
	return t.btrienode128 == nil
}

func (t *tree128) findBestMatch(key []uint32, ln byte) (bool, *btrienode128, *btrienode128) {
	var (
		exact   bool
		cparent *btrienode128
		parent  *btrienode128
		node    = t.btrienode128
	)
	for node != nil && node.match(key, ln) {
		if parent != nil && parent.dummy == 0 {
			cparent = parent
		}
		if DEBUG != nil {
			if node.dummy != 0 {
				fmt.Fprintf(DEBUG, "dummy %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			} else {
				fmt.Fprintf(DEBUG, "found %s for %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln))
			}
		}
		parent = node
		if node.prefixlen == ln {
			exact = true
			break
		}
		if hasBit(key, parent.prefixlen+1) {
			node = node.a
		} else {
			node = node.b
		}
	}
	return exact, parent, cparent
}

func (t *tree128) addRoute(key []uint32, ln byte, value unsafe.Pointer, replace bool) (set bool, oldval unsafe.Pointer) {
	if ln > 128 {
		panic("Unable to add prefix longer than 128")
	}
	set = true
	if t.btrienode128 == nil {
		// just starting a tree
		if DEBUG != nil {
			fmt.Fprintf(DEBUG, "root=%s (no subtree)\n", keyStr(key, ln))
		}
		t.btrienode128 = t.newnode(key[:(ln+31)/32], ln, 0)
		return
	}
	var (
		exact bool
		node  *btrienode128
		down  *btrienode128
	)
	if exact, node, _ = t.findBestMatch(key, ln); exact {
		if node.dummy != 0 {
			node.dummy = 0
			node.data = value
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "setting empty child's %v/%d value\n", key, ln)
			}
		} else {
			oldval = node.data
			if replace {
				node.data = value
			} else {
				set = false // this is only time we don't set
			}
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "hit previously set %v/%d node\n", key, ln)
			}
		}
		return
	}
	newnode := t.newnode(key[:(ln+31)/32], ln, 0)
	if node != nil {
		if hasBit(key, node.prefixlen+1) {
			if node.a == nil {
				node.a = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "a-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.a
			down = node.a
		} else {
			if node.b == nil {
				node.b = newnode
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "b-child %s for %s\n", keyStr(key, ln), keyStr(node.bits[:], node.prefixlen))
				}
				return
			}
			// newnode fits between node and node.b
			down = node.b
		}
	} else {
		// newnode goes in front of root node
		down = t.btrienode128
	}

	parent := node
	if parent != nil && parent.prefixlen >= ln {
		panic("parent's prefix could not be larger than key len")
	}

	matched := down.bitsMatched(key, ln)
	if matched > ln {
		matched = ln
	}

	if matched == ln { // matched >=ln to remove that if above
		// down matches key fully, so new branch would start from here
		var plen byte = 1
		if parent != nil {
			// also make sure we're not messed up branch direction
			plen = parent.prefixlen + 1
		}
		use_a := hasBit(newnode.bits[:], plen)
		if use_a != hasBit(down.bits[:], plen) {
			panic("something is wrong with branch that we intend to append to")
		}
		if use_a {
			newnode.a = down
		} else {
			newnode.b = down
		}
		if parent != nil {
			if hasBit(newnode.bits[:], plen) {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.a = newnode
			} else {
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(key, ln), keyStr(parent.bits[:], parent.prefixlen), keyStr(down.bits[:], down.prefixlen))
				}
				parent.b = newnode
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(key, ln), keyStr(down.bits[:], down.prefixlen), m)
			}
			t.btrienode128 = newnode
		}
	} else {
		// down and newnode should have new empty parent
		node = t.newnode(key[:(ln+31)/32], matched, 1)
		use_a := hasBit(down.bits[:], matched+1)
		if use_a == hasBit(newnode.bits[:], matched+1) {
			panic("tangled branches while creating new intermediate parent")
		}
		if use_a {
			node.a = down
			node.b = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created a-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(down.bits[:], down.prefixlen), keyStr(key, ln))
			}
		} else {
			node.b = down
			node.a = newnode
			if DEBUG != nil {
				fmt.Fprintf(DEBUG, "created b-dummy %s with %s and %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), keyStr(down.bits[:], down.prefixlen))
			}
		}

		//insert b-child 1.2.3.0/25 to 1.2.3.0/24 before 1.2.3.0/29
		if parent != nil {
			if hasBit(newnode.bits[:], parent.prefixlen+1) {
				parent.a = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert a-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.a.bits[:], node.a.prefixlen))
				}
			} else {
				parent.b = node
				if DEBUG != nil {
					fmt.Fprintf(DEBUG, "insert b-child %s to %s before %s\n", keyStr(node.bits[:], node.prefixlen), keyStr(parent.bits[:], parent.prefixlen), keyStr(node.b.bits[:], node.b.prefixlen))
				}
			}
		} else {
			if DEBUG != nil {
				m := "b"
				if use_a {
					m = "a"
				}
				fmt.Fprintf(DEBUG, "root=%s (uses %s as %s-child)\n", keyStr(node.bits[:], node.prefixlen), keyStr(key, ln), m)
			}
			t.btrienode128 = node
		}
	}
	return
}

func New128() *Trie128 {
	return &Trie128{new(tree128)}
}

func (rt *Trie128) Get(ip []byte, mask byte) (bool, []byte, byte, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	exact, node, ct := rt.findBestMatch(u32, mask)

	if node != nil && node.dummy == 0 {
		// dummy node means "no match"
		return exact, utoip(node.bits[:], node.prefixlen), node.prefixlen, node.data
	}

	if ct != nil {
		// accept container as the answer if it's present
		return false, utoip(ct.bits[:], ct.prefixlen), ct.prefixlen, ct.data
	}
	return false, nil, 0, nil

}

func (rt *Trie128) Append(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, false)
	return set, olval
}

func (rt *Trie128) Set(ip []byte, mask byte, value unsafe.Pointer) (bool, unsafe.Pointer) {
	u32 := iptou(ip, mask)
	set, olval := rt.addRoute(u32, mask, value, true)
	return set, olval
}
